---
# När applikationen startar på din laptop
server:
  port: 8081
management:
  server:
    port: 8091
---
# När applikationen startar i OpenShift
spring:
  profiles: openshift
server:
  port: 8080
management:
  security:
    enabled: false
  server:
    port: 8090
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true